version: '3'
services:
  node:
    build: .
    working_dir: "/usr/src/app"
    command:
      [ "yarn", "run", "dev" ]
    ports:
      - "3000:3000"
    volumes:
      - "/usr/src/app/node_modules"
      - ".:/usr/src/app"
